### ISSUE TITLE
Saving function on windows machine throws an exception 

### ISSUE THREAD

**Issue by SKununka** [jason-p-pickering/datim-validation#14]
Hello Jason,
I am using a windows machine and running the R validation package. This runs okay and I get the out put  but when I try to save I cannot run this command directly 
> write.csv(violation,file='uganda_violations_Sol.csv')
when I do I get this error

Error in .External2(C_writetable, x, file, nrow(x), p, rnames, sep, eol,  : 
  unimplemented type 'list' in 'EncodeElement'

but when I first run the following commands in sequence then I am able to save the output.
> violation<-plyr::colwise(as.character)(violation)
> write.csv(violation,file='uganda_violations_Sol.csv')

Thankyou 
Solomon Kununka (Uganda)

**Comment by jason-p-pickering** [comment]
Hi Solomon,
Thanks for reporting this issue. Could you please update your code to the latest release with 

`library(devtools)
install_github("jason-p-pickering/datim-validation")`

and see if you still get this error?

**Comment by SKununka** [comment]
Great will do so.Thanks much for the update.
Solomon Kununka
Uganda

**Comment by jason-p-pickering** [comment]
Thanks. if you still have issues let me know. 

Regards,
Jason
