### ISSUE TITLE
Check mechanism validity against the period of data submission

### ISSUE THREAD

**Issue by jason-p-pickering** [jason-p-pickering/datim-validation#17]
Data should only be allowed to be entered when the mechanism is active for the time period in which data is being imported. Currently, the check is not strict enough.

**Comment by jason-p-pickering** [comment]
Data from invalid mechanisms is leaking into the imports. We need to validate that the time period of import is fully within the start/end dates of the mechanism.

**Comment by mmwebaze** [comment]
Hi Jason,

I have tested 'getInvalidMechanisms' on Uganda data import file submitted in ticket #4237 on HelpDesk and the following are returned as invalid mechanisms: U6CehXJlPCh and alMZIpFmpxf

Regards,

Michael

**Comment by jason-p-pickering** [comment]
Should be taken care  of in a5de981f294b6cc2ccb3d5971b26add4eba29c4a
