### ISSUE TITLE
Issue trying to run getValidOperatingUnits.R function 

### ISSUE THREAD

**Issue by Green-EyE** [jason-p-pickering/datim-validation#18]
Hi 
I'm trying to list all valid Operating Units using "getValidOperatingUnits", but I'm getting the following error :

> check_oU <- getValidOperatingUnits (base.url, username, password)
Error: could not find function "getValidOperatingUnits"

Can clarify what is wrong ?

Thanks in advance
Green-EyE

**Comment by jason-p-pickering** [comment]
Please send you full script on this ticket so I can attempt to reproduce it.

**Comment by Green-EyE** [comment]
Hi Jason
You can get the script from https://github.com/jason-p-pickering/datim-validation/blob/master/R/getValidOperatingUnits.R

Also I'm attaching it

Thanks
Green_EyE
[getValidOperatingUnits.txt](https://github.com/jason-p-pickering/datim-validation/files/303025/getValidOperatingUnits.txt)

**Comment by jason-p-pickering** [comment]
I know where I can get the script but thanks.

Where is your R script which loads and utilizes this library function?

Did you follow the Readme and consult the vignette of how to get started?

**Comment by Green-EyE** [comment]
Yes I've followed all the instructions in vignette  https://github.com/jason-p-pickering/datim-validation/blob/master/vignettes/validating_data.Rmd
I was able to test all the scripts that I wanted except this one

Attached the file I'm using to test.

Thanks for your support, please let me know if have additional questions

Green_EyE
[TargetExportXML_Testing.txt](https://github.com/jason-p-pickering/datim-validation/files/304145/TargetExportXML_Testing.txt)

**Comment by jason-p-pickering** [comment]
Hi @Green-EyE ,
Please do not post data which may be confidential to this public repository. If this was test data, it is fine, otherwise, the data which you posted (if real) should not be posted to this repo. I have remove that post. 

What you sent was the data. What I am asking for is the R script which you actually ran. 

Please do not send any usernames or passwords. You should remove these prior to posting here. My script looks something like this

```
require(datimvalidation)
username = "admin"
password ="district"
base.url = "https://www.datim.org/"
setwd("~/moz/2016Oct/")
filename<-"~/moz/2016Oct/TargetExportXML20160412165917.txt"
organisationUnit = "XXXXXXX"

d<-d2Parser(file=filename,type = "xml",
            base.url = base.url,
            username = username,password = password,
            organisationUnit = organisationUnit,
            dataElementIdScheme = "code",orgUnitIdScheme = "code",idScheme = "code"  )
invalid_des<-getInvalidDataElements(d,base.url,username,password)
doMC::registerDoMC(cores=4) # or however many cores you have access to
parallel=TRUE


getInvalidMechanisms(d,base.url,username,password,organisationUnit)
invalid_des<-getInvalidDataElements(d,base.url,username,password)
vr_violations<-validateData(data = d,base.url = base.url,
                            username = username,password = password)
```
If I understand you correctly, you are having problems with a particular function, but everything else works fine?

**Comment by Green-EyE** [comment]
Ooops....sorry for the inconvenience, I totally agree with confidentiality rules. Thanks for deleting it.
Yes, I having problems with a this particular function returning an error :: 

check_oU <- getValidOperatingUnits 
Error: object 'getValidOperatingUnits' not found 

Green_EyE

**Comment by jason-p-pickering** [comment]
@Green-EyE , I have pushed a new fix for this in 61d2121e5c018ea22c4fa781c3103bb3289ea0a2. Thanks for reporting. Please reinstall from source with 

```
library(devtools)
install_github("jason-p-pickering/datim-validation")
library(datimvalidation)
```

After that, it should work. Otherwise, please reopen this issue.

**Comment by mmwebaze** [comment]
Hi Jason,

I am unable to effect the new changes. I am getting the following error: Error in eapply(ns_env(pkg), force, all.names = TRUE)

**Comment by jason-p-pickering** [comment]
@mmwebaze , can you please provide the command/log which results in this error?

**Comment by jason-p-pickering** [comment]
@mmwebaze , here is what I did, and it worked. 
```
library(devtools)
install_github("jason-p-pickering/datim-validation")
library(datimvalidation)
username = "XXXX"
password ="XXXXX"
base.url = "XXXXX"
getValidOperatingUnits(base.url,username,password)
```
which then returneda list of 36 Operating Units.

                               name          id
1                            Angola XOivy2uDpMF
....

**Comment by mmwebaze** [comment]
Hi Jason,

that is exactly what I did and got the following message see attachment.
![eapply-error](https://cloud.githubusercontent.com/assets/7035644/16005377/fd16d78a-3134-11e6-9e13-02a73380024c.png)

**Comment by jason-p-pickering** [comment]
@mmwebaze this does not seem to be a problem really with this package, but rather the "devtools" package and or R on Windows. I will try and test on a Windows machine and see if I can reproduce.

**Comment by jason-p-pickering** [comment]
@mmwebaze , it seems you are using a quite old version of R. Could you try and upgrade to a later version and try again if possible?

https://cran.r-project.org/bin/windows/base/

**Comment by mmwebaze** [comment]
Thanks Jason,

Updated devtools and curl now it is running.

**Comment by jason-p-pickering** [comment]
Great @mmwebaze . Thanks. Closing this issue again for now.
