### ISSUE TITLE
Getting Invalid OrgUnit's script

### ISSUE THREAD

**Issue by Green-EyE** [jason-p-pickering/datim-validation#19]
Dear Jason
I'm using this repository to validated my XML file and I would like to validated the OrgUnit's code by running a script.

Can you please help ?

Green-EyE

**Comment by Green-EyE** [comment]
anyone to help !!!!

**Comment by jason-p-pickering** [comment]
Hi there.

You can use the getOrganisationUnitMap method to obtain a map of all of the
organization units for your operating unit.

**Comment by Green-EyE** [comment]
Is there a way to list all missing orgUnit in case that they are present in my XML file but not yet in Datim ?


Thanks
Cicero
