### ISSUE TITLE
Retrieve imported data by period

### ISSUE THREAD

**Issue by Green-EyE** [jason-p-pickering/datim-validation#20]
Hi Jason,
I would like to able to retrieve imported data by period and download to a Excel file.

Green-EyE

**Comment by Green-EyE** [comment]
anyone to help !!!!

**Comment by jason-p-pickering** [comment]
Please consult the dhis2 documentation and specifically the API developer
documents.  The datim validation package does not currently support this
operation.

**Comment by Green-EyE** [comment]
Ok, thank you.
