### ISSUE TITLE
issue with getExactDuplicates

### ISSUE THREAD

**Issue by Green-EyE** [jason-p-pickering/datim-validation#27]
Hi JP
I'm running this script to check for duplicates 
check_dup <- getExactDuplicates(d)

and is returning 38 obs, but actually there's no duplication in the file
[ResultExportXML20160923171828-Ultimo - Copy.txt](https://github.com/jason-p-pickering/datim-validation/files/490155/ResultExportXML20160923171828-Ultimo.-.Copy.txt)

Can you help clarify this issue ?

Thanks
G

**Comment by mmwebaze** [comment]
@Green-EyE 

I have run this file and it does have duplicates... 
Looking at the first two duplicates for p.mz.1.Military, you have
"EjdjNEKUqUE","2016Q2","siMZUtd2cJW","XkqnsV4slkA","ns9iYmAt2PK","432"
"EjdjNEKUqUE","2016Q2","siMZUtd2cJW","XkqnsV4slkA","ns9iYmAt2PK","180"

Mechanism (17723 - FADM Prevention and Circumcision Program) has uid ns9iYmAt2PK while data element 'HTC_TST_N_DSD_Results' is EjdjNEKUqUE

Which value should be considered?

Thanks,

Michael

**Comment by jason-p-pickering** [comment]
Please be careful of posting any actual data on this public repository.

**Comment by Green-EyE** [comment]
Hi Michael and Jason
Thanks for your support, I've manage to solve the issue.


Green-EyE
