### ISSUE TITLE
Returning strange error for getOrgnisationUnitMap

### ISSUE THREAD

**Issue by Green-EyE** [jason-p-pickering/datim-validation#28]
I'm getting a strange error after I load datavalidation, username, password, base.url and OrganisationUnit

getOrganisationUnitMap(base.url,username, password,organisationUnit)
Error in getOrganisationUnitMap(base.url, username, password, organisationUnit) : 
  unused arguments (username, password, organisationUnit)

Can you assist?

Thanks
G

**Comment by mmwebaze** [comment]
Hi Green-EYE,

the function getOrganisationUnitMap only accepts a single parameter. See the source code below

https://github.com/jason-p-pickering/datim-validation/blob/master/R/getOrganisationUnitMap.R

Regards,

Michael

**Comment by Green-EyE** [comment]
Hi Michael,
Thanks for you promptly response, I've realize that I was mistaking on my secrets file. I've solved the issue.

G
