### ISSUE TITLE
getValidDataElements returns empty rows for datasets of formType Default

### ISSUE THREAD

**Issue by mmwebaze** [jason-p-pickering/datim-validation#31]
In validating a file with a data element that belongs to a dataset of formType other than 'CUSTOM' such as 'Default' returns the data element as invalid. The R script (getValidDataElements.R) returns empty rows for datasets of formType 'Default'.

**Comment by jason-p-pickering** [comment]
This is caused due to the lack of an HTML form . We need to check for this first and then if it does not exist fall back to the data elements assigned to the dataset.

**Comment by jason-p-pickering** [comment]
@mmwebaze I have looked at this think it was due to a mismatch in the two different views which are used to get the valid data elements. I have made a change in DATIM production which I think should correct this. Could you try again?

**Comment by mmwebaze** [comment]
@jason-p-pickering I still get 'Site Tiered support' as an invalid data element. When I add the dataset id to the vector of datasets passed to getInvalidDataElements(data = d, datasets), I get 'invalid input, please try again' error

**Comment by jason-p-pickering** [comment]
@mmwebaze , OK, thanks for the detailed report. I will have a look.

**Comment by jason-p-pickering** [comment]
Finally managed to get to this and it should be fixed in 3c75cb75aa65b9a
