### ISSUE TITLE
validateData throws Errors

### ISSUE THREAD

**Issue by mmwebaze** [jason-p-pickering/datim-validation#32]
@jason-p-pickering 

In validating SIMS related data, the validateData is throwing the following error which I suspect is windows related. 

Error in `$<-.data.frame`(`*tmp*`, "combi", value = ".") : 
  replacement has 1 row, data has 0

FYI @ManishUNC

**Comment by jason-p-pickering** [comment]
@mmwebaze this is likely being thrown because there are no  validation rules for SIMS. I will look into it, but do not think its a high priority issue as validation rules are not implmented for SIMS.

**Comment by jason-p-pickering** [comment]
@mmwebaze I think that this has been fixed due to re-implementation of a few methods. Closing for now, but if you see it again, please let me know.
