### ISSUE TITLE
Error in sims parser R script

### ISSUE THREAD

**Issue by vshioshvili** [jason-p-pickering/datim-validation#34]
Error is being thrown when trying to run sims parser against the hrsa data file;

> d=sims2Parser(file=filename)
Error in if ((start_date - end_date) < nrow(bar)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In sims2Parser(file = filename) :
  214  rows are incomplete. Please check your file to ensure its correct.

Data file is in zendesk ticket: https://datim.zendesk.com/agent/tickets/6189

**Comment by jason-p-pickering** [comment]
@vshioshvili I think this has been corrected.
