### ISSUE TITLE
Validation is not working for LAB Indiators

### ISSUE THREAD

**Issue by Green-EyE** [jason-p-pickering/datim-validation#39]
Dear team,
Validation rules check are failing return when I try to run only LAB indicators file:

vr_violations<-validateData(data = d,
                            return_violations_only = TRUE,
                             parallel = FALSE )
Warning message:
In validateData(data = d, return_violations_only = TRUE, parallel = FALSE) :
  NAs introduced by coercion

Regards
Cicero

**Comment by jason-p-pickering** [comment]
Cannot reproduce this, but I think it is not applicable.
