### ISSUE TITLE
How to download data

### ISSUE THREAD

**Issue by Green-EyE** [jason-p-pickering/datim-validation#42]
Hi everyone,
Any clue in how to download data from a specific reporting period (dataelemnt, categoryOptionCombo, attributeOptionCombo, orgUnit, value) using R or Querying the Browser ?

Thanks
G

**Comment by Green-EyE** [comment]
I'm trying the following script but it's failing:

#We are going to need these two libraries
require(RCurl)
require(XML)
#This is a URL endpoint for a report table which we can 
#get from the WebAPI. 
url<-"https://www.datim.org/api/reportTables/EM3AhEeBcR1/data.csv"
#Lets get the response and we do not need the headers
#This site has some issues with its SSL certificate
#so lets not verify it.
response<-getURL(url,user="myUser",userpwd="myPass"
,httpauth = 1L, header=FALSE,ssl.verifypeer = FALSE)
#Unquote the data
data<-noquote(response)
#here is the data.
mydata<-read.table(textConnection(data),sep=",",header=T)
head(mydata)

**Comment by jason-p-pickering** [comment]
@Green-EyE have a look at https://docs.dhis2.org/master/en/developer/html/webapi_data_values.html#webapi_reading_data_values. The script you provide there is for reading an SQL view, but not for directly working with the data value API.
