### ISSUE TITLE
sims parser invalidData bug

### ISSUE THREAD

**Issue by vshioshvili** [jason-p-pickering/datim-validation#43]
In sims2Parser, there is a bug that makes invalidData attribute pointless. On line 133, if statement checks if there are invalid records, and if true, removes them instead of using the invalidData parameter to decide; I believe it should be this:

    if (!invalidData) {
      data <- data[!invalid.rows, ]
    }

instead of current:

    if (sum(invalid.rows)) {
      data <- data[!invalid.rows, ]
    }

**Comment by jason-p-pickering** [comment]
@vshioshvili Could you have another look at this after 1148ca62737ff ?
