### ISSUE TITLE
supporting header-less file in d2parser

### ISSUE THREAD

**Issue by vshioshvili** [jason-p-pickering/datim-validation#48]
Jason,

In sims workflow I use both d2parser and sims2parser. I use d2parser output for two reasons: check if there are duplicates, and also to have "original" period-assessment id mapping. sims2parser shifts dates, and one of the outputs agencies asked is summary of assessments that got shifted; i use outputs of the two parsers to generate that.

in the original SIMS guidance agencies were told that they can send files with header missing if they so desire. Unfortunately, most agencies are following that suggestions. sims2parser has a boolean option that treats missing header appropriately. d2parser does not have that, and ends up ignoring the first row if the header is not present.

Would it be possible to add missing header option to d2parser as well, similar to sims2parser? I could try to make the change and do a pull request if that would make things easier.

**Comment by jason-p-pickering** [comment]
Sure sounds reasonable. 

A lot of that code needs to be centralized, but for now, it seems reasonable to just modify it as an optional parameter with a default value so that we do not break existing scripts which may not need this.
