### ISSUE TITLE
Determine technical approach for deprecated rules

### ISSUE THREAD

**Issue by chris-githu** [jason-p-pickering/datim-validation#51]
Hi @jason-p-pickering 

While validating Malawi's import file [ZD10488](https://datim.zendesk.com/agent/tickets/10488), I noticed that `datim-validation` is subjecting the data to this validation rule 
- https://www.datim.org/api/validationRules/xMAzvvGL8Hi 
However, based on the data entry form (and updated data elements this quarter), the following rule should be applied instead 
- https://www.datim.org/api/validationRules/N0pTGdWb7pe

N.B Both rules refer to the same left side element 
- [TX_NEW_N_DSD_Preg_Feeding](https://www.datim.org/api/dataElements/QI0LrOAmBCG) 
but different right side elements
- [TX_NEW_N_DSD](https://www.datim.org/api/dataElements/tG7ocyZ8kVA) *Old Rule*
- [TX_NEW_N_DSD_HIVStatus](https://www.datim.org/api/dataElements/BunPg5H6AL9) *New Rule*

The data entry form in DATIM applies the correct rule as seen below

![correct validation rule](https://user-images.githubusercontent.com/13725334/36018172-d00dd646-0d8b-11e8-9933-32f7e9131473.PNG)

Please advise.
Thanks.

FYI @talexie @ManishUNC

**Comment by jason-p-pickering** [comment]
@chris-githu this is really a false positive. The validation scripts are doing what they should, and as you see, the validation also occurs in the same way on the server. There is no association (purposefully) between validation rules and datasets in DHIS2, so this old rule is still being applied even though it is really deprecated. 

I think we need a new issue in the MERTide repo, which would indicate (perhaps through a data store object) which validation rules are applicable to which time period or to deprecate rules which are no longer applicable, like the one you point out. 

I think in this case, we should inform the user that the violation is a false positive.

**Comment by vshioshvili** [comment]
@chris-githu after talking with Jason yesterday, we have a solution for this. I've made the change and is in the pull request https://github.com/jason-p-pickering/datim-validation/pull/53 

@jason-p-pickering @talexie @ManishUNC

**Comment by jason-p-pickering** [comment]
Should be fixed by @vshioshvili  in 8cf4e99380a57b4d304afeb0de49deb635564365
