### ISSUE TITLE
use of unwise characters in DHIS2 urls

### ISSUE THREAD

**Issue by vshioshvili** [jason-p-pickering/datim-validation#54]
In a number of places datim-validation library uses characters deemed unwise that Tomcat started to disallow. In 7.0.90 url containing [ and/or ] gets trimmed and results in a 400 request from DHIS2. In 7.0.85 Tomcat did not filter those out.

As DHIS2 uses [ and ] for providing array of field names (at least that is the main use that appears in the datim-validation), they need to be escaped. 

I do not have a full list of places, but here is an example: getDataElementMap.R include [ and ] in the url, and with tomcat 7.0.90, calling getDataElementMap function results in a null, as opposed to the data element map in 7.0.85.

**Comment by jason-p-pickering** [comment]
@vshioshvili thanks for the report. Strange that this happens, since the URL should be encoded by the `URLencode` function. (https://github.com/jason-p-pickering/datim-validation/blob/master/R/getDataElementMap.R#L10) 

I will have a look at it and thanks for the bug report.

**Comment by jason-p-pickering** [comment]
From [here](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/URLencode.html) 

```
In addition, ! $ & ' ( ) * + , ; = : / ? @ # [ ] are reserved characters, and should be encoded unless used in their reserved sense, which is scheme specific. The default in URLencode is to leave them alone, which is appropriate for file:// URLs, but probably not for http:// ones.
```

**Comment by vshioshvili** [comment]
@jason-p-pickering if you need environment to test against, my dev instance - vshioshvili.datim.org has 7.0.90 and your account is enabled with super user.

**Comment by vshioshvili** [comment]
@jason-p-pickering looks like unless you specify reserved=TRUE it won't alter them.

**Comment by vshioshvili** [comment]
@jason-p-pickering i have a suspicion that this might not work as expected.

this is the code in getDataElementMap.R:

``` url<-URLencode(paste0(getOption("baseurl"),"api/dataElements?fields=id,code,shortName,name,numberType,optionSet[id]&paging=false"))```

problem is that from the above, characters like ?, &, and = are also "reserved", so above call will result in those being escaped as well, producing invalid URL.

also, based on the stackoverflow article you shared on DATIM Global issue, [ and ] are unwise, as opposed to others being reserved.

https://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid/1547940#1547940

**Comment by jason-p-pickering** [comment]
Investigate https://cran.r-project.org/web/packages/urltools/vignettes/urltools.html

**Comment by vshioshvili** [comment]
> URLencode(paste0("dev-de.datim.org/","api/dataElements?fields=id,code,shortName,name,numberType,optionSet[id]&paging=false"))
[1] "dev-de.datim.org/api/dataElements?fields=id,code,shortName,name,numberType,optionSet[id]&paging=false"
> URLencode(paste0("dev-de.datim.org/","api/dataElements?fields=id,code,shortName,name,numberType,optionSet[id]&paging=false"), reserved=TRUE)
[1] "dev-de.datim.org%2Fapi%2FdataElements%3Ffields%3Did%2Ccode%2CshortName%2Cname%2CnumberType%2CoptionSet%5Bid%5D%26paging%3Dfalse"

**Comment by jason-p-pickering** [comment]
@vshioshvili I am going to close this, because I think its more of an issue with Tomcat and DHIS2, than intrinsically an issue with these scripts. Once DHIS2 removes the "unsmart" characters, we can make changes here, and until then, those administering Tomcat will need to allow these characters. 

Let me know if you think this is not correct by re-opening this ticket.
