### ISSUE TITLE
Use of ts variable

### ISSUE THREAD

**Issue by vikwato** [jason-p-pickering/datim-validation#64]
if(nrow(invalidPeriod) != 0){
  write.csv(invalidPeriod, paste0(path, '_invalidPeriod', ts, '.csv'), na="") }

Hi Jason, it might not be an appropriate place but I was looking at an example of the R Script for datim validation. What is the variable, ts, used for? It's not initialized anywhere.

**Comment by vikwato** [comment]
Is it timestamp?

**Comment by jason-p-pickering** [comment]
@vikwato could you point me to line of the source code where you found this? 

I checked in the latest version, and could not find it anywhere. 

Thanks for the report!

**Comment by vikwato** [comment]
[Guidance for Validating of Data Payloads for DATIM Using R Validation Package.pdf](https://github.com/jason-p-pickering/datim-validation/files/2880233/Guidance.for.Validating.of.Data.Payloads.for.DATIM.Using.R.Validation.Package.pdf)

**Comment by vikwato** [comment]
![image](https://user-images.githubusercontent.com/12084633/53019889-72da7380-345e-11e9-9787-de43b679ed82.png)
 take for example this piece of code?

**Comment by jason-p-pickering** [comment]
@vikwato this is other code which is not part of this package, so I will proceed to close this issue.
