### ISSUE TITLE
getMechanismMap error when giving regional country UID

### ISSUE THREAD

**Issue by sam-bao** [jason-p-pickering/datim-validation#65]
For example Barbados

datimvalidation::getMechanismsMap("RKoVudgb05Y")
Error in as.Date.default(sapply(mechs$categoryOptions, function(x) ifelse(is.null(x$startDate),  : 
  c("do not know how to convert 'sapply(mechs$categoryOptions, function(x) ifelse(is.null(x$startDate), ' to class “Date”", "do not know how to convert '    \"1900-01-01\", x$startDate))' to class “Date”")

As discussed I am feeding it a UID other than an Operating Unit so an error is expected, but could be caught earlier and with a more informative message.

**Comment by jason-p-pickering** [comment]
Should be handled better in bf9feeaf430c43ad35e5bc8778db3cfb84ac9fb5. 

getMechanismsMap will return NULL if there are no mechanisms. When checking for invalid mechanisms, an error will be returned.
