### ISSUE TITLE
getValidDataElements throwing error after DHIS2 upgrade

### ISSUE THREAD

**Issue by sam-bao** [jason-p-pickering/datim-validation#67]
The function call I am attempting:

  `datimvalidation::getValidDataElements("nIHNMxuPUOR")`

The error message:

  ```Error in `[.data.frame`(des, , names(des.all)) : 
    undefined columns selected```

 This appears to result from a difference in the structure of a response from DHIS2 2.3 vs 2.29.

This server running 2.3 at the moment
https://www.datim.org/api/29/sqlViews/DotdxKrNZxG/data.json?var=dataSets:nIHNMxuPUOR&paging=false

This server running 2.29 at the moment
https://jason.datim.org/api/29/sqlViews/DotdxKrNZxG/data.json?var=dataSets:nIHNMxuPUOR&paging=false

We can see that the responses from the API differ

![https___jason_datim_org_api_29_sqlViews_DotdxKrNZxG_data_json_var_dataSets_nIHNMxuPUOR_paging_false_and_https___www_datim_org_api_29_sqlViews_DotdxKrNZxG_data_json_var_dataSets_nIHNMxuPUOR_paging_false_and_Top_10_Roof_Dormer_Types__Plus_Cos.png](https://images.zenhubusercontent.com/5a828d624b5806bc2bc6b2d2/91d1407e-eca5-4c30-8871-c56754c37b9e)

**Comment by jason-p-pickering** [comment]
Fixed in 96c6cb369fb54fb8289d90f7add396e11a2d40be. Be sure to restart (and possibly upgrade R to the latest version).
