### ISSUE TITLE
error due to recent changes

### ISSUE THREAD

**Issue by vshioshvili** [jason-p-pickering/datim-validation#70]
@jason-p-pickering after recent changes to datim-validation to make the code work with 2.30, the following error started occurring:

```
> de_disags <- checkDataElementDisaggValidity(d, ds)
Error in `[.data.frame`(des, , names(des.all)) : 
  undefined columns selected
```

**Comment by jason-p-pickering** [comment]
Someone else reported this as well. Seems that you need to restart (and possibly upgrade R) and all dependencies. There were a lot of dependency upgrades here unfortunately.
