### ISSUE TITLE
value type compliance for true_only data type

### ISSUE THREAD

**Issue by vshioshvili** [jason-p-pickering/datim-validation#74]
https://github.com/jason-p-pickering/datim-validation/blob/master/R/checkValueTypeCompliance.R#L39 allows only `true` for TRUE_ONLY type, but DHIS2 recognizes/accepts `True`, `true`, and `1` as a valid value for TRUE_ONLY data element type. I am not sure about BOOLEAN (I have not looked).

The problem is that EMR_SITE data element for DATIM is set up as TRUE_ONLY, and import files that have a 1 get imported correctly, but checkValueTypeCompliance flags them as invalid, making it inconsistent with DHIS2.

**Comment by jason-p-pickering** [comment]
Resolved in 31fcaaffcb4cd075d1f01f8eb0e7267dbf6547b3
