### ISSUE TITLE
scientific notation issue with d2parser

### ISSUE THREAD

**Issue by vshioshvili** [jason-p-pickering/datim-validation#86]
If there is a large number of records in the input file (e.g. 600k records) R is forcing scientific notation on larger values (e.g. `50000` becomes `5e+05`) which results in value type compliance issues to be triggered.

Note, this is not an issue with a small file, and if a file only has a handful of records, it does not apply scientific notation, and everything is working as expected.

I am able to prevent the issue by setting the scipen option at the start of the script though:

`options(scipen=999)`

**Comment by jason-p-pickering** [comment]
Noted this in the documentation in 1c3f196288984c4330a998d673376623a20e1401
