### ISSUE TITLE
inconsistency in d2session use in method signatures

### ISSUE THREAD

**Issue by vshioshvili** [jason-p-pickering/datim-validation#88]
While most method signatures default recently introduced d2session attribute to d2_default_session, created by datimutils:: loginToDATIM function (unless a different variable name is provided), this one https://github.com/jason-p-pickering/datim-validation/blob/master/R/checkDataElementOrgunitValidity.R#L100 does not, breaking code that does not specify the d2session variable explicitly.

**Comment by jason-p-pickering** [comment]
Should be fixed in 86c7147386772c14823adca872a83a64c66a743b
