### ISSUE TITLE
Couldn't find function loadSecrets

### ISSUE THREAD

**Issue by kwebihaf-github** [jason-p-pickering/datim-validation#91]
Hello,

 When I run` loadSecrets(secrets)` an error is returned.

The error is `Error in loadSecrets(secrets) : could not find function "loadSecrets"`

I am running `datimvalidation` package version `1.0.112`

**Comment by jason-p-pickering** [comment]
Did you load the package?

**Comment by kwebihaf-github** [comment]
> Did you load the package?

Yes I did

**Comment by jason-p-pickering** [comment]
@kwebihaf-github this function has been deprecated. Please refer to the vignette for detailed instructions about the latest version. In short, you will need to use the function "loginToDATIM" from the datimutils package https://github.com/pepfar-datim/datimutils
