### ISSUE TITLE
caching is no longer working

### ISSUE THREAD

**Issue by vshioshvili** [jason-p-pickering/datim-validation#93]
Since the migration to datimutils package for logging into and maintaining DHIS2 session information, caching of metadata no longer works. No longer available `loadSecrets` method set option [maxCacheAge](https://github.com/jason-p-pickering/datim-validation/commit/7f2401b2bfd79dea2f0db188ad08be0ebab8700e#diff-8b124cf6b080ba70e77206a840754c97f09297eacf7cc2b088e5efc873ac5fdaL122) but now that there is no code that sets the option, code that retrieves cached objects consistently returns NULL (e.g. [here](https://github.com/jason-p-pickering/datim-validation/blob/86c7147386772c14823adca872a83a64c66a743b/R/internals.R#L30))

**Comment by jason-p-pickering** [comment]
Updated the vignette with instructions about how to get the caching working again by setting an option in 61e5ff51d8f31f786c765915c5b0b8d28a52109e
